# PATHS
TEMP_FOLDER = "TEMP/"
ANNOTATIONS_FOLDER = TEMP_FOLDER + "annotations/"
VIDEOS_FOLDER = TEMP_FOLDER + "videos/"
SPEAKERS_FOLDER = TEMP_FOLDER + "speakers/"
SEGMENTS_FOLDER = TEMP_FOLDER + "segments/"
RAPID_ANNOTATOR_FILE = "static/annotated.xlsx"

# MODEL
MAX_SEQ_LENGTH = 20
NUM_FEATURES = 1024
IMG_SIZE = 128
EPOCHS = 5
BATCH_SIZE = 32
